export default data = {
	status: 'OK',
	request_id: 'b92981dc-e052-4b77-a7d6-3554e7c5202f',
	parameters: {
		query: 'react developer',
		page: 1,
		num_pages: 1,
	},
	data: [
		{
			job_id: 'HQ6bOBBaXycFbww5AAAAAA==',
			employer_name: 'Dice',
			employer_logo:
				'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0',
			employer_website: null,
			employer_company_type: 'Information',
			job_publisher: 'LinkedIn',
			job_employment_type: 'FULLTIME',
			job_title: 'Full Stack React Developer',
			job_apply_link: 'https://www.linkedin.com/jobs/view/full-stack-react-developer-at-dice-3897013434',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.6276,
			apply_options: [
				{
					publisher: 'LinkedIn',
					apply_link: 'https://www.linkedin.com/jobs/view/full-stack-react-developer-at-dice-3897013434',
					is_direct: false,
				},
				{
					publisher: 'Dice.com',
					apply_link: 'https://www.dice.com/job-detail/47953827-ff21-4dfe-87cc-6ac264573a42',
					is_direct: true,
				},
				{
					publisher: 'Fullstack Jobs - OnSite And Remote Full Stack Jobs',
					apply_link: 'https://fullstackjob.com/job/2emNZ2UIjz95MTimbM7p9VsW5kJ',
					is_direct: false,
				},
				{
					publisher: 'React Jobs',
					apply_link:
						'https://reactjsjob.com/job/2emNNfbtncblCsPXHPTzHSYVCNt/Full%20Stack%20React%20Developer',
					is_direct: false,
				},
				{
					publisher: 'Trabajo.org',
					apply_link: 'https://us.trabajo.org/job-2463-a8edb141cc3df6839107fecc5273ea02',
					is_direct: false,
				},
				{
					publisher: 'Lensa',
					apply_link:
						'https://lensa.com/job/phoenix-staff-inc/phoenix-az/full-stack-developer/525a014defa1411b6e5565ffd6ff3538',
					is_direct: false,
				},
				{
					publisher: 'Jobilize',
					apply_link:
						'https://www.jobilize.com/job/us-az-phoenix-full-stack-react-developer-staff-hiring-now-job-immediately',
					is_direct: false,
				},
			],
			job_description:
				"Dice is the leading career destination for tech experts at every stage of their careers. Our client, Phoenix Staff, Inc., is seeking the following. Apply via Dice today!\n\nTitle: Full Stack React Developer\n\nLocation: Phoenix, AZ or Indianapolis, IN\n\nWe are looking for a skilled Full Stack React Developer to join our clients team! Our client builds custom software products with a specialization in engineering digital solutions that empower Utilities providers and their partners. Their team of Engineers, Strategists, and Software Consultants delivers the right web/mobile solutions, with an unwavering commitment to quality. Our client prides themselves on being Innovation Partners, navigating today's challenges and anticipating the solutions of tomorrow.\n\nAs a Full Stack React Developer, you ll play a pivotal role in driving the growth of our client's product development team. You will have the opportunity to make a tangible impact on clients and projects, crafting solutions that solve complex problems and drive business success. You'll collaborate closely with clients and teammates, sharing your expertise, and contributing to a culture of continuous learning and improvement.\n\nThis role is fully remote; however, we are looking for candidates residing in the Phoenix and Indianapolis metropolitan areas.\n\nKey Responsibilities:\n• Develop web and mobile applications using React.js, React Native and Node.js\n• Educate and advise clients and teammates on technical options/trends\n• Participate in client consultations to help brainstorm, answer questions, and build solutions\n• Perform scoping/architecture and product requirements for new and ongoing projects\n• Work within an Agile Scrum framework and manage day-to-day communication with project counterparts\n• Analyze, design, implement and integrate functional requirements in new or existing solutions\n• Effectively communicate with stakeholders about goals, plans, deliverables, timelines, and the status of your work, ensuring on-time and on-budget delivery\n\nRequirements:\n• Extensive hands-on experience (3+ years) with React.js, React Native, and Node.js, including proficiency in building robust and scalable web and mobile applications.\n• Demonstrated ability (2+ years) in engaging with clients to understand requirements, define project scopes, and provide technical recommendations, or equivalent consulting experience in a client-facing role.\n• Special consideration given to candidates with proficiency in multiple programming languages with the ability to adapt and learn new technologies as needed.\n• Proven track record of deploying web and mobile applications, showcasing expertise in the entire software development lifecycle from design to deployment.\n• Formal training in computer science or related field, such as completion of boot camps or relevant coursework. Equivalent on-the-job experience will also be considered.\n• Proficiency in project management tools such as Jira and Confluence, ensuring efficient collaboration and communication within the team and with stakeholders.\n• Experience with version control systems, particularly Git, for managing code repositories and facilitating collaborative development workflows.\n• Experience with database systems such as MySQL, PostgreSQL, or MongoDB\n• Ability to work collaboratively in a team environment, with excellent communication and problem-solving skills.",
			job_is_remote: false,
			job_posted_at_timestamp: 1712957497,
			job_posted_at_datetime_utc: '2024-04-12T21:31:37.000Z',
			job_city: 'Phoenix',
			job_state: 'AZ',
			job_country: 'US',
			job_latitude: 33.448376,
			job_longitude: -112.074036,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=HQ6bOBBaXycFbww5AAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-05-12T21:31:37.000Z',
			job_offer_expiration_timestamp: 1715549497,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: null,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: true,
				degree_mentioned: false,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'Extensive hands-on experience (3+ years) with React.js, React Native, and Node.js, including proficiency in building robust and scalable web and mobile applications',
					'Demonstrated ability (2+ years) in engaging with clients to understand requirements, define project scopes, and provide technical recommendations, or equivalent consulting experience in a client-facing role',
					'Special consideration given to candidates with proficiency in multiple programming languages with the ability to adapt and learn new technologies as needed',
					'Proven track record of deploying web and mobile applications, showcasing expertise in the entire software development lifecycle from design to deployment',
					'Formal training in computer science or related field, such as completion of boot camps or relevant coursework',
					'Equivalent on-the-job experience will also be considered',
					'Proficiency in project management tools such as Jira and Confluence, ensuring efficient collaboration and communication within the team and with stakeholders',
					'Experience with version control systems, particularly Git, for managing code repositories and facilitating collaborative development workflows',
					'Experience with database systems such as MySQL, PostgreSQL, or MongoDB',
					'Ability to work collaboratively in a team environment, with excellent communication and problem-solving skills',
				],
				Responsibilities: [
					"As a Full Stack React Developer, you ll play a pivotal role in driving the growth of our client's product development team",
					'You will have the opportunity to make a tangible impact on clients and projects, crafting solutions that solve complex problems and drive business success',
					"You'll collaborate closely with clients and teammates, sharing your expertise, and contributing to a culture of continuous learning and improvement",
					'Develop web and mobile applications using React.js, React Native and Node.js',
					'Educate and advise clients and teammates on technical options/trends',
					'Participate in client consultations to help brainstorm, answer questions, and build solutions',
					'Perform scoping/architecture and product requirements for new and ongoing projects',
					'Work within an Agile Scrum framework and manage day-to-day communication with project counterparts',
					'Analyze, design, implement and integrate functional requirements in new or existing solutions',
					'Effectively communicate with stakeholders about goals, plans, deliverables, timelines, and the status of your work, ensuring on-time and on-budget delivery',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113300',
			job_onet_job_zone: '4',
			job_naics_code: '519130',
			job_naics_name: 'Internet Publishing and Broadcasting and Web Search Portals',
		},
		{
			job_id: '6L-6LJxHftlpKzapAAAAAA==',
			employer_name: '1 Point System',
			employer_logo: null,
			employer_website: null,
			employer_company_type: null,
			job_publisher: 'Dice.com',
			job_employment_type: 'CONTRACTOR',
			job_title: 'React Developer - 10+ years of exp. needed',
			job_apply_link: 'https://www.dice.com/job-detail/8fb9aea2-8efd-4dd9-837f-6bda26256644',
			job_apply_is_direct: true,
			job_apply_quality_score: 0.6008,
			apply_options: [
				{
					publisher: 'Dice.com',
					apply_link: 'https://www.dice.com/job-detail/8fb9aea2-8efd-4dd9-837f-6bda26256644',
					is_direct: true,
				},
				{
					publisher: 'React Jobs',
					apply_link:
						'https://reactjsjob.com/job/2f0V0iGa1hFGAKYWb2TsRnPrX6G/React%20Developer%20-%2010+%20years%20of%20exp.%20needed%20(Reactjs)',
					is_direct: false,
				},
			],
			job_description:
				'Title: React Developer\nRole: Hybrid in Charlotte, NC\nDuration: 11 months Contract to hire\n\nExp.:\n10+ years of experience\n\nProject: Team builds rich front-end experiences for horizontals like Digital Pro and ePRO.\n\nSkills:\nFront end engineering experience, on large customer facing applications\nReact\nNode\nRedux experience\nRetail/ecommerce experience is desirable.',
			job_is_remote: false,
			job_posted_at_timestamp: 1712936152,
			job_posted_at_datetime_utc: '2024-04-12T15:35:52.000Z',
			job_city: 'Charlotte',
			job_state: 'NC',
			job_country: 'US',
			job_latitude: 35.227085,
			job_longitude: -80.843124,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=6L-6LJxHftlpKzapAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-05-13T15:35:52.000Z',
			job_offer_expiration_timestamp: 1715614552,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 120,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: ['react', 'redux', 'node'],
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: false,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'10+ years of experience',
					'Project: Team builds rich front-end experiences for horizontals like Digital Pro and ePRO',
					'Front end engineering experience, on large customer facing applications',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
		},
		{
			job_id: 'lk9z3xNNuOdpCEpNAAAAAA==',
			employer_name: 'Virtue Group',
			employer_logo: null,
			employer_website: null,
			employer_company_type: null,
			job_publisher: 'Jooble',
			job_employment_type: 'CONTRACTOR',
			job_title: 'React Developer',
			job_apply_link: 'https://jooble.org/jdp/-5800529153607138872',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.5496,
			apply_options: [
				{
					publisher: 'Jooble',
					apply_link: 'https://jooble.org/jdp/-5800529153607138872',
					is_direct: false,
				},
				{
					publisher: 'Salary.com',
					apply_link: 'https://www.salary.com/job/virtue-group/react-developer/j202404100404082877986',
					is_direct: false,
				},
			],
			job_description:
				'Currently, we are looking for talented resources for one of our listed clients. If interested please reply to me with your updated resume or feel free to reach out to me for more details at\n\nTitle: React Developer\n\nLocation: Dallas, TX or Miami, FL (Onsite)\n\nDuration: 12+ Months Contract\n\nMinimum Qualifications:\n• Bachelor s degree in Computer Science, Software Engineering, or related field.\n• 3 - 5+ years of experience in web application development, with at least 3 years focused on React and modern JavaScript frameworks.\n• Proven expertise in designing and implementing micro-frontend architectures.\n• Strong understanding of web technologies (HTML, CSS/SCSS, JavaScript) and experience with RESTful services and APIs.\n• Familiarity with DevSecOps tools and practices, including CI/CD pipelines, containerization (Docker, Kubernetes), and cloud services (AWS, Azure, Google Cloud).\n• Excellent problem-solving skills, ability to think strategically, and strong leadership qualities.\n• Effective communication skills, capable of articulating technical concepts to non-technical stakeholders.\n\nDesired Skills:\n• Advanced React.js Knowledge: Expert-level understanding of React.js, its core principles, lifecycle, state management, hooks, and context API.\n• Micro-Frontend Architecture: Proven experience in designing, implementing, and managing micro-frontend architectures, including module federation and dynamic module loading.\n• JavaScript Proficiency: Deep knowledge of modern JavaScript (ES6+), including understanding of asynchronous request handling, partial page updates, and AJAX.\n• HTML5 & CSS3: Strong skills in creating responsive and adaptive designs using HTML5 and CSS3, including pre-processors like SASS or LESS.\n• State Management Tools: Experience with state management libraries (e.g., Redux, MobX) and their integration with React applications.\n• Testing Frameworks: Familiarity with testing frameworks and libraries such as Jest, Enzyme, or React Testing Library, including unit, integration, and end-to-end testing practices.\n• Build Tools: Proficiency in using build tools like Webpack, Rollup, or Parcel for bundling and optimizing web applications.\n• Version Control: Extensive experience with version control systems, particularly Git, including branching strategies and collaborative development workflows.\n• RESTful APIs: Experience with consuming RESTful services and APIs, understanding the principles of REST, and experience with GraphQL is a plus.\n• CI/CD Pipelines: Knowledge of continuous integration and continuous deployment practices, including familiarity with tools like Jenkins, CircleCI, or GitHub Actions.\nReport this job\n• Dice Id: 91116358\n• Position Id: 8252049',
			job_is_remote: false,
			job_posted_at_timestamp: 1712858488,
			job_posted_at_datetime_utc: '2024-04-11T18:01:28.000Z',
			job_city: 'Miami',
			job_state: 'FL',
			job_country: 'US',
			job_latitude: 25.76168,
			job_longitude: -80.19179,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=lk9z3xNNuOdpCEpNAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-05-10T00:00:00.000Z',
			job_offer_expiration_timestamp: 1715299200,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 36,
				experience_mentioned: true,
				experience_preferred: true,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: true,
				degree_preferred: true,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'Bachelor s degree in Computer Science, Software Engineering, or related field',
					'3 - 5+ years of experience in web application development, with at least 3 years focused on React and modern JavaScript frameworks',
					'Proven expertise in designing and implementing micro-frontend architectures',
					'Strong understanding of web technologies (HTML, CSS/SCSS, JavaScript) and experience with RESTful services and APIs',
					'Familiarity with DevSecOps tools and practices, including CI/CD pipelines, containerization (Docker, Kubernetes), and cloud services (AWS, Azure, Google Cloud)',
					'Excellent problem-solving skills, ability to think strategically, and strong leadership qualities',
					'Effective communication skills, capable of articulating technical concepts to non-technical stakeholders',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
		},
		{
			job_id: 'HD05fSgWlWhi2PSUAAAAAA==',
			employer_name: 'ECS',
			employer_logo: 'https://ecstech.com/wp-content/uploads/2023/04/ecs-new-logo.png',
			employer_website: 'http://ecstech.com',
			employer_company_type: 'Consulting',
			job_publisher: 'LinkedIn',
			job_employment_type: 'FULLTIME',
			job_title: 'React Developer',
			job_apply_link: 'https://www.linkedin.com/jobs/view/react-developer-at-ecs-3895410074',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.6531,
			apply_options: [
				{
					publisher: 'LinkedIn',
					apply_link: 'https://www.linkedin.com/jobs/view/react-developer-at-ecs-3895410074',
					is_direct: false,
				},
				{
					publisher: 'Indeed',
					apply_link: 'https://www.indeed.com/viewjob?jk=159d227672cdc4dd',
					is_direct: false,
				},
				{
					publisher: 'Talentify',
					apply_link:
						'https://www.talentify.io/job/react-developer-washington-district-of-columbia-ecs-14656',
					is_direct: false,
				},
				{
					publisher: 'BeBee',
					apply_link: 'https://us.bebee.com/job/ab331dee80f4c271bd1faf2c23b8a9d1',
					is_direct: false,
				},
			],
			job_description:
				'ECS is seeking a React Developer to work in our Washington, DC office .\n\nJob Description:\n\nECS is seeking a TS-cleared React Developer to support one of our mission critical programs for the Department of Justice. We offer the chance to support the world’s finest law enforcement organization and help the people that keep us safe. In this job you will support agents, analysts, and professionals and technology they use to fight terrorism, espionage, cyber-attacks, and major criminal threats.\n\nWe are seeking candidates committed to high quality to provide courteous and accurate technical information. As a React Developer, you will collaborate with customers, often engaging directly with non-technical personnel, to understand their data related needs, suggest solutions, and complete work in a timely manner. This position performs activities associated with implementation, integration, and support of computer systems in mission-critical response operations environment.\n\nResponsibilities:\n• Design and develop User Interfaces (UIs) and UI components using React.\n• Design and implement key front-end features and services.\n• Develop and optimize user-facing features and services.\n• Develop software/applications using AWS technologies.\n• Design, code, test, and debug applications and software solutions.\n• Troubleshoot, debug, and optimize code and interface software/applications.\n• Gather and evaluate user feedback and make recommendations for improvement.\n• Analyze system capabilities to resolve problems.\n\nRequired Skills:\n• Bachelor’s degree in Computer Science, Information Systems, Engineering, or a related technical discipline\n• Active Top Secret with SCI eligibility\n• 4+ years overall hands-on application programming experience\n• 3+ years of experience designing and implementing User Interfaces (UIs) and UI components\n• 3+ years of demonstrated coding experience in React\n• Solid foundational knowledge, understanding and experience with JavaScript\n• 2+ years Cloud experience (AWS preferred)\n• Experience optimizing front-end performance and features\n• Significant knowledge and experience with SQL and NoSQL databases\n• Experience working with source control systems like Git, Gitlab in an application development environment\n• Working knowledge and experience with Agile Scrum methodology\n\nDesired Skills:\n• AWS Certification.\n• Experience with implementing scalability within an AWS Cloud infrastructure.\n• Willingness to learn new skills and technologies on the fly.\n• Ability to communicate with customers to refine requirements.\n• Being a team player, willing to transparently collaborate with technical SMEs.\n\nECS is an equal opportunity employer and does not discriminate or allow discrimination on the basis of race, color, religion, sex, age, sexual orientation, gender identity or expression, national origin, ancestry, citizenship, genetic information, registered domestic partner status, marital status, status as a crime victim, disability, protected veteran status, or any other characteristic protected by law. ECS promotes affirmative action for minorities, women, disabled persons, and veterans.\n\nECS is a leading mid-sized provider of technology services to the United States Federal Government. We are focused on people, values and purpose. Every day, our 3800+ employees focus on providing their technical talent to support the Federal Agencies and Departments of the US Government to serve, protect and defend the American People.',
			job_is_remote: false,
			job_posted_at_timestamp: 1712872650,
			job_posted_at_datetime_utc: '2024-04-11T21:57:30.000Z',
			job_city: 'Washington',
			job_state: 'DC',
			job_country: 'US',
			job_latitude: 38.907192,
			job_longitude: -77.03687,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=HD05fSgWlWhi2PSUAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-05-11T21:57:30.000Z',
			job_offer_expiration_timestamp: 1715464650,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 48,
				experience_mentioned: true,
				experience_preferred: true,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: true,
				degree_mentioned: true,
				degree_preferred: true,
				professional_certification_mentioned: true,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'Bachelor’s degree in Computer Science, Information Systems, Engineering, or a related technical discipline',
					'Active Top Secret with SCI eligibility',
					'4+ years overall hands-on application programming experience',
					'3+ years of experience designing and implementing User Interfaces (UIs) and UI components',
					'3+ years of demonstrated coding experience in React',
					'Solid foundational knowledge, understanding and experience with JavaScript',
					'Experience optimizing front-end performance and features',
					'Significant knowledge and experience with SQL and NoSQL databases',
					'Experience working with source control systems like Git, Gitlab in an application development environment',
					'Working knowledge and experience with Agile Scrum methodology',
				],
				Responsibilities: [
					'As a React Developer, you will collaborate with customers, often engaging directly with non-technical personnel, to understand their data related needs, suggest solutions, and complete work in a timely manner',
					'This position performs activities associated with implementation, integration, and support of computer systems in mission-critical response operations environment',
					'Design and develop User Interfaces (UIs) and UI components using React',
					'Design and implement key front-end features and services',
					'Develop and optimize user-facing features and services',
					'Develop software/applications using AWS technologies',
					'Design, code, test, and debug applications and software solutions',
					'Troubleshoot, debug, and optimize code and interface software/applications',
					'Gather and evaluate user feedback and make recommendations for improvement',
					'Analyze system capabilities to resolve problems',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
			job_naics_code: '54161',
			job_naics_name: 'Management Consulting Services',
		},
		{
			job_id: 'GdkTAFXu4nv4EVSdAAAAAA==',
			employer_name: 'Rush Order',
			employer_logo: null,
			employer_website: null,
			employer_company_type: null,
			job_publisher: 'Indeed',
			job_employment_type: 'FULLTIME',
			job_title: 'React Developer',
			job_apply_link: 'https://www.indeed.com/viewjob?jk=6a8d622fcce1266f',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.6167,
			apply_options: [
				{
					publisher: 'Indeed',
					apply_link: 'https://www.indeed.com/viewjob?jk=6a8d622fcce1266f',
					is_direct: false,
				},
				{
					publisher: 'Glassdoor',
					apply_link:
						'https://www.glassdoor.com/job-listing/react-developer-rush-order-JV_KO0,15_KE16,26.htm?jl=1009227722574',
					is_direct: false,
				},
			],
			job_description:
				"Help Rush Order build amazing customer experiences\n\nWho we look for\n\nRush Order is growing quickly and we are continuously looking for smart, personable, highly motivated individuals. If you are interested in joining a fast-paced team delivering awesome solutions for amazing brands, please review our current openings below and apply today!\n\nReact Developer\n\nSummary\n\nRush Order is on the hunt for a talented React Developer. As a member of our team, you'll work on exciting projects that are changing the game in the world of e-commerce and fulfillment. You will be responsible for designing, developing, and implementing complex web applications using React and related technologies. You will work closely with cross-functional teams to deliver high-quality software solutions that meet the needs of our clients in the logistics and warehouse industries.\n\nLocated just a stone's throw away from the tech hub of Silicon Valley, our team is at the forefront of innovation in this rapidly evolving field. If you're ready to join an exciting, dynamic team that's taking e-commerce and fulfillment to new heights, then apply now and become a part of our legacy!\n\nResponsibilities\n\nDesign and develop high-quality web applications using React and related technologies.\n\nCollaborate with designers, product owners, and stakeholders to understand requirements and develop solutions.\n\nImplement and maintain code using best practices and design patterns.\n\nOptimize applications for performance and scalability.\n\nTroubleshoot and debug issues as they arise.\n\nContinuously learn and stay up-to-date with new tools, frameworks, and technologies.\n\nWork collaboratively with other developers and team members to ensure project goals are met.\n\nRequirements\n\nBachelor's degree in Computer Science or related field.\n\nProven experience in developing web applications using React and related technologies.\n\nStrong knowledge of JavaScript, HTML, and CSS.\n\nFamiliarity with Git and agile development methodologies.\n\nExperience working in logistics or warehouse operations is a plus.\n\nExcellent problem-solving skills and attention to detail.\n\nStrong communication and collaboration skills.\n\nIf you are passionate about developing innovative software solutions for logistics and warehouse operations and are excited about working in a dynamic and fast-paced environment, we encourage you to apply for this position.\n\nJob Type: Full-time\n\nPay: $80,000.00 - $110,000.00 per year\n\nBenefits:\n\n401(k)\n\nDental insurance\n\nFlexible schedule\n\nFlexible spending account\n\nHealth insurance\n\nHealth savings account\n\nLife insurance\n\nPaid time off\n\nReferral program\n\nVision insurance\n\nExperience level:\n\n1 year\n\nSchedule:\n\n8 hour shift\n\nChoose your own hours\n\nMonday to Friday\n\nWork Location: Hybrid remote in Gilroy, CA 95020",
			job_is_remote: false,
			job_posted_at_timestamp: 1712624930,
			job_posted_at_datetime_utc: '2024-04-09T01:08:50.000Z',
			job_city: null,
			job_state: null,
			job_country: 'US',
			job_latitude: 37.09024,
			job_longitude: -95.71289,
			job_benefits: ['paid_time_off', 'health_insurance', 'dental_coverage', 'retirement_savings'],
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=GdkTAFXu4nv4EVSdAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-08-09T02:17:08.000Z',
			job_offer_expiration_timestamp: 1723169828,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: null,
				experience_mentioned: true,
				experience_preferred: true,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: true,
				degree_preferred: true,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: 80000,
			job_max_salary: 110000,
			job_salary_currency: 'USD',
			job_salary_period: 'YEAR',
			job_highlights: {
				Qualifications: [
					"Bachelor's degree in Computer Science or related field",
					'Proven experience in developing web applications using React and related technologies',
					'Strong knowledge of JavaScript, HTML, and CSS',
					'Familiarity with Git and agile development methodologies',
					'Excellent problem-solving skills and attention to detail',
					'Strong communication and collaboration skills',
					'If you are passionate about developing innovative software solutions for logistics and warehouse operations and are excited about working in a dynamic and fast-paced environment, we encourage you to apply for this position',
					'1 year',
				],
				Responsibilities: [
					'You will be responsible for designing, developing, and implementing complex web applications using React and related technologies',
					'You will work closely with cross-functional teams to deliver high-quality software solutions that meet the needs of our clients in the logistics and warehouse industries',
					'Collaborate with designers, product owners, and stakeholders to understand requirements and develop solutions',
					'Implement and maintain code using best practices and design patterns',
					'Optimize applications for performance and scalability',
					'Troubleshoot and debug issues as they arise',
					'Continuously learn and stay up-to-date with new tools, frameworks, and technologies',
					'Work collaboratively with other developers and team members to ensure project goals are met',
				],
				Benefits: [
					'Pay: $80,000.00 - $110,000.00 per year',
					'401(k)',
					'Dental insurance',
					'Flexible schedule',
					'Flexible spending account',
					'Health insurance',
					'Health savings account',
					'Life insurance',
					'Paid time off',
					'Referral program',
					'Vision insurance',
					'Choose your own hours',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
		},
		{
			job_id: '0sekFxGrczQ-uz-OAAAAAA==',
			employer_name: 'Ehub Global Inc',
			employer_logo:
				'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvgS2qgP-hjDbBUIstJ9zb2pJw-Js9dNXQ7DFy&s=0',
			employer_website: null,
			employer_company_type: null,
			job_publisher: 'LinkedIn',
			job_employment_type: 'CONTRACTOR',
			job_title: 'React Developer',
			job_apply_link: 'https://www.linkedin.com/jobs/view/react-developer-at-ehub-global-inc-3891225872',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.631,
			apply_options: [
				{
					publisher: 'LinkedIn',
					apply_link: 'https://www.linkedin.com/jobs/view/react-developer-at-ehub-global-inc-3891225872',
					is_direct: false,
				},
				{
					publisher: 'React.js Jobs',
					apply_link: 'https://react.cafe/jobs/57528465-react-developer',
					is_direct: false,
				},
			],
			job_description:
				'Title: React Developer\n\nLocation: Remote (New York)\n\nDuration: 6+ months, likely to be long-term\n\nRequirements:\n\n5 years of progressive Software Engineering experience with a focus in front-end development with React and other JavaScript Libraries.\n\nBackend development experience ideally with Ruby or Ruby on Rails.\n\nExperience refactoring/reengineering large applications.',
			job_is_remote: true,
			job_posted_at_timestamp: 1712874525,
			job_posted_at_datetime_utc: '2024-04-11T22:28:45.000Z',
			job_city: 'New York',
			job_state: 'NY',
			job_country: 'US',
			job_latitude: 40.712776,
			job_longitude: -74.005974,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=0sekFxGrczQ-uz-OAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-05-11T22:28:45.000Z',
			job_offer_expiration_timestamp: 1715466525,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 60,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: true,
				degree_mentioned: false,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: 60,
			job_max_salary: 65,
			job_salary_currency: 'USD',
			job_salary_period: 'HOUR',
			job_highlights: {
				Qualifications: [
					'5 years of progressive Software Engineering experience with a focus in front-end development with React and other JavaScript Libraries',
					'Backend development experience ideally with Ruby or Ruby on Rails',
					'Experience refactoring/reengineering large applications',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
		},
		{
			job_id: 'SwU7ODAgesNQKllhAAAAAA==',
			employer_name: 'Deloitte',
			employer_logo:
				'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Deloitte.svg/1200px-Deloitte.svg.png',
			employer_website: 'http://www.deloitte.com',
			employer_company_type: 'Consulting',
			job_publisher: 'Clearance Jobs',
			job_employment_type: 'FULLTIME',
			job_title: 'React Developer SS Jobs',
			job_apply_link: 'https://www.clearancejobs.com/jobs/7668864/react-developer-ss',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.5584,
			apply_options: [
				{
					publisher: 'Clearance Jobs',
					apply_link: 'https://www.clearancejobs.com/jobs/7668864/react-developer-ss',
					is_direct: false,
				},
			],
			job_description:
				'Are you an experienced, passionate pioneer in technology - a solutions builder, a roll-up-your-sleeves technologist who wants a daily collaborative environment, think-tank feel and share new ideas with your colleagues - without the extensive demands of travel? If so, consider an opportunity with our US Delivery Center - we are breaking the mold of a typical Delivery Center.\n\nOur US Delivery Centers have been growing since 2014 with significant, continued growth on the horizon. Interested? Read more about our opportunity below...\n\nThe Team- Digital Customer\n\nOur Digital Customer team focuses on designing and implementing sales and service experiences, capabilities, and architectures to bring customer strategies to life. Our ambition is to be the best in the world at driving customer transformation through the development of clever commercial strategies, distinctive experiences, and the application of digital technologies. We help make the "creative digital consultancy" real and in doing so, make new markets.\n\nProfessionals will serve our clients through the following types of work:\n• Sales Excellence & Service Excellence | delivers sales and service strategies and plans, operating model definition, incentive design and implementation, and operations support for digitally-enabled sales, channel, and customer service capabilities\n• Digital Experience | creates engaging omni-channel digital experiences across web, mobile, AR/VR, voice, gesture, IoT, and video\n• Flexible Consumption | the commercial strategy, operating model definition, and capability delivery of subscription/flexible consumption business models\n• Digital Foundry | a flexible, end-to-end delivery model emphasizing innovation and disruption\n• DigitalMix | an integrated set of platforms to enable business re-platforming\n\nWork you\'ll do\n• Responsible for supporting and independently completing project tasks\n• Developing new user-facing features using React.js\n• Building reusable components and front-end libraries for future use\n• Translating designs and wireframes into high quality code\n• Optimizing components for maximum performance across a vast array of web-capable devices and browsers\n• Participate in daily stand-ups, bi-weekly sprint planning, and sprint retrospectives for the team\n• Develop solutions to client problems through application of methods and tools; validates solutions to subject matter experts\n\nQualifications Required\n• 3+ years of experience with the design and development of single page web applications\n• Bachelor\'s degree, preferably in Computer Science, Information Technology, Computer Engineering, or related IT discipline; or equivalent experience\n• Experience in React.js and its core principles such as React patterns, state management libraries (such as Flux or Redux), Props drilling, data sharing among React components\n• Experience with JavaScript, including DOM manipulation and the JavaScript object model\n• Experience in HTML5, CSS3 and Less/Sass and of any CSS frameworks (Bootstrap or Material Design)\n• Experience using RESTful APIs and integration with React.js\n• Experience with responsive web design and implementing web accessibility standards in code\n• Experience with common front-end development tools such as Babel, Webpack, NPM etc. and data structure libraries (e.g. Immutable.js)\n• Experience with security best practices and modern authorization mechanisms, such as JSON Web Token\n• Must live in a commutable distance (approximately 100-mile radius) to one of the following Delivery locations: Atlanta, GA; Charlotte, NC; Dallas, TX; Gilbert, AZ; Houston, TX; Lake Mary, FL; Mechanicsburg, PA; Philadelphia, PA with the ability to commute to assigned location for the day, without the need for overnight accommodations\n• Expectation to co-locate in your designated Delivery location up to 30% of the time based on business needs. This may include a maximum of 10% overnight client/project travel.\n• Must be legally authorized to work in the United States without the need for employer sponsorship, now or at any time in the future.\n• Must be able to obtain the required level of security clearance for this role.\n\nQualifications Preferred\n• Knowledge of Node.js\n• Familiarity with other front-end languages and frameworks like jQuery, Angular, and Vue.js\n\nInformation for applicants with a need for accommodation:\n\nhttps://www2.deloitte.com/us/en/pages/careers/articles/join-deloitte-assistance-for-disabled-applicants.html',
			job_is_remote: false,
			job_posted_at_timestamp: 1712728646,
			job_posted_at_datetime_utc: '2024-04-10T05:57:26.000Z',
			job_city: 'Mechanicsburg',
			job_state: 'PA',
			job_country: 'US',
			job_latitude: 40.21327,
			job_longitude: -77.00803,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=SwU7ODAgesNQKllhAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: '2024-06-09T00:00:26.000Z',
			job_offer_expiration_timestamp: 1717891226,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 36,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: true,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'3+ years of experience with the design and development of single page web applications',
					"Bachelor's degree, preferably in Computer Science, Information Technology, Computer Engineering, or related IT discipline; or equivalent experience",
					'Experience in React.js and its core principles such as React patterns, state management libraries (such as Flux or Redux), Props drilling, data sharing among React components',
					'Experience with JavaScript, including DOM manipulation and the JavaScript object model',
					'Experience in HTML5, CSS3 and Less/Sass and of any CSS frameworks (Bootstrap or Material Design)',
					'Experience using RESTful APIs and integration with React.js',
					'Experience with responsive web design and implementing web accessibility standards in code',
					'Experience with common front-end development tools such as Babel, Webpack, NPM etc',
					'and data structure libraries (e.g. Immutable.js)',
					'Experience with security best practices and modern authorization mechanisms, such as JSON Web Token',
					'Must live in a commutable distance (approximately 100-mile radius) to one of the following Delivery locations: Atlanta, GA; Charlotte, NC; Dallas, TX; Gilbert, AZ; Houston, TX; Lake Mary, FL; Mechanicsburg, PA; Philadelphia, PA with the ability to commute to assigned location for the day, without the need for overnight accommodations',
					'Must be legally authorized to work in the United States without the need for employer sponsorship, now or at any time in the future',
					'Must be able to obtain the required level of security clearance for this role',
				],
				Responsibilities: [
					'Sales Excellence & Service Excellence | delivers sales and service strategies and plans, operating model definition, incentive design and implementation, and operations support for digitally-enabled sales, channel, and customer service capabilities',
					'Responsible for supporting and independently completing project tasks',
					'Developing new user-facing features using React.js',
					'Building reusable components and front-end libraries for future use',
					'Translating designs and wireframes into high quality code',
					'Optimizing components for maximum performance across a vast array of web-capable devices and browsers',
					'Participate in daily stand-ups, bi-weekly sprint planning, and sprint retrospectives for the team',
					'Develop solutions to client problems through application of methods and tools; validates solutions to subject matter experts',
					'Expectation to co-locate in your designated Delivery location up to 30% of the time based on business needs',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
			job_naics_code: '541613',
			job_naics_name: 'Marketing Consulting Services',
		},
		{
			job_id: 'albrpEGQyc9i3URhAAAAAA==',
			employer_name: 'Upwork',
			employer_logo: 'https://image.status.io/z6aeO6kAGsAG.png',
			employer_website: 'http://www.elance.com',
			employer_company_type: 'Computer Services',
			job_publisher: 'Upwork',
			job_employment_type: 'CONTRACTOR',
			job_title: 'Experienced React Developer Needed for Exciting Web Project. ONLY USE OR EUROPE',
			job_apply_link: 'https://www.upwork.com/freelance-jobs/apply/React-Developer_~0104d7301969bd68a0/',
			job_apply_is_direct: true,
			job_apply_quality_score: 0.6851,
			apply_options: [
				{
					publisher: 'Upwork',
					apply_link: 'https://www.upwork.com/freelance-jobs/apply/React-Developer_~0104d7301969bd68a0/',
					is_direct: true,
				},
			],
			job_description:
				'We are seeking a skilled React developer to join our team and collaborate on an exciting web project. As our React Developer, you will be responsible for implementing user interface components using React.js concepts and workflows such as Redux, Flux, and Webpack. The ideal candidate should have a strong understanding of JavaScript, HTML5, and CSS3, along with experience in integrating RESTful APIs. Location: remote\n\nRequirements:\n\n- Proficiency in React.js and its core principles\n\n- Experience with popular React.js workflows (such as Redux)\n\n- Familiarity with RESTful APIs\n\n- Strong understanding of JavaScript, HTML5, and CSS3\n\n- Experience with version control systems (e.g., Git)\n\n- Excellent communication and teamwork skills\n\nIf you are passionate about creating exceptional web applications using React.js and are looking for an engaging project to contribute to, we would love to hear from you! Please include examples of your previous work and your availability.',
			job_is_remote: true,
			job_posted_at_timestamp: 1712835999,
			job_posted_at_datetime_utc: '2024-04-11T11:46:39.000Z',
			job_city: null,
			job_state: null,
			job_country: 'US',
			job_latitude: 37.09024,
			job_longitude: -95.71289,
			job_benefits: null,
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=albrpEGQyc9i3URhAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: null,
			job_offer_expiration_timestamp: null,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: null,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: ['React', 'JavaScript', 'CSS', 'HTML', 'Redux'],
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: false,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: 20,
			job_max_salary: 50,
			job_salary_currency: 'USD',
			job_salary_period: 'HOUR',
			job_highlights: {
				Qualifications: [
					'The ideal candidate should have a strong understanding of JavaScript, HTML5, and CSS3, along with experience in integrating RESTful APIs',
					'Proficiency in React.js and its core principles',
					'Experience with popular React.js workflows (such as Redux)',
					'Familiarity with RESTful APIs',
					'Experience with version control systems (e.g., Git)',
					'Excellent communication and teamwork skills',
					'If you are passionate about creating exceptional web applications using React.js and are looking for an engaging project to contribute to, we would love to hear from you!',
				],
				Responsibilities: [
					'As our React Developer, you will be responsible for implementing user interface components using React.js concepts and workflows such as Redux, Flux, and Webpack',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
			job_naics_code: '541511',
			job_naics_name: 'Custom Computer Programming Services',
		},
		{
			job_id: 'o-wK-4w8ZR5DaDUTAAAAAA==',
			employer_name: 'United Airlines',
			employer_logo: 'https://logowik.com/content/uploads/images/617_unitedairlines.jpg',
			employer_website: 'http://www.united.com',
			employer_company_type: 'Logistics',
			job_publisher: 'United Airlines Jobs',
			job_employment_type: 'FULLTIME',
			job_title: 'Senior React Developer - Information Technology',
			job_apply_link:
				'https://careers.united.com/us/en/job/WHQ00023518/Senior-React-Developer-Information-Technology',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.8081,
			apply_options: [
				{
					publisher: 'United Airlines Jobs',
					apply_link:
						'https://careers.united.com/us/en/job/WHQ00023518/Senior-React-Developer-Information-Technology',
					is_direct: false,
				},
				{
					publisher: 'LinkedIn',
					apply_link:
						'https://www.linkedin.com/jobs/view/senior-react-developer-information-technology-at-united-airlines-3886158885',
					is_direct: false,
				},
				{
					publisher: 'Equality Magazines',
					apply_link:
						'https://equalitymagazines.com/chicago-il/senior-react-developer-information-technology/54A27182249D42EAA57AF6935E91DF24/job/',
					is_direct: false,
				},
				{
					publisher: 'Indeed',
					apply_link: 'https://www.indeed.com/viewjob?jk=37c1d064c3bf4626',
					is_direct: false,
				},
				{
					publisher: 'ZipRecruiter',
					apply_link:
						'https://www.ziprecruiter.com/c/United-Airlines,-Inc/Job/Senior-React-Developer-Information-Technology/-in-Chicago,IL?jid=59c9a5a2e873af40',
					is_direct: false,
				},
				{
					publisher: 'Glassdoor',
					apply_link:
						'https://www.glassdoor.com/job-listing/senior-react-developer-information-technology-united-airlines-JV_IC1128808_KO0,45_KE46,61.htm?jl=1009222673209',
					is_direct: false,
				},
				{
					publisher: 'Ladders',
					apply_link:
						'https://www.theladders.com/job/senior-react-developer-information-technology-unitedairlinesholdingsinc-chicago-il_69997148',
					is_direct: false,
				},
				{
					publisher: 'SimplyHired',
					apply_link:
						'https://www.simplyhired.com/job/6yCggMJaCy2G-RCc6zuFdqzD1vc8FjTU4OvgaEOU73ss3cs9otuGrQ',
					is_direct: false,
				},
			],
			job_description:
				'Description\n\nThere’s never been a more exciting time to join United Airlines! We’re on a path towards becoming the best airline in the history of aviation. Our shared purpose – Connecting People, Uniting the World – is about more than getting people from one place to another. It also means that as a global company that operates in hundreds of locations around the world with millions of customers and tens of thousands of employees, we have a unique responsibility to uplift and provide opportunities in the places where we work, live and fly, and we can only do that with a truly diverse and inclusive workforce. And we’re growing – in the years ahead, we’ll hire tens of thousands of people across every area of the airline. Our careers include a competitive benefits package aimed at keeping you happy, healthy and well-traveled. From employee-run "Business Resource Group" communities to world-class benefits like parental leave, 401k and privileges like space available travel, United is truly a one-of-a-kind place to work. Are you ready to travel the world?\n\nWe believe that inclusion propels innovation and is the foundation of all that we do. United\'s Digital Technology team spans the globe and is made up of diverse individuals all working together with pioneering technology to build the best airline in the history of aviation. Our team designs, develops and maintains massively scaling technology solutions brought to life with innovative architectures, data analytics, and digital solutions.\n\nJob overview and responsibilities\n\nThe Senior Developer plays a Critical role in creating and maintaining the strategic partnership between business needs and technology delivery. The Senior Developer\'s role is to lead the efforts to plan, design, develop and launch efficient systems and solutions in support of core organizational functions. This individual will apply proven communication, analytical and problem-solving skills to help identify, communicate and resolve issues, opportunities or problems in order to enhance the benefit of IT and Business investments. The Principal Developer is highly experienced and has decision-making authority. The Principal Developer is self - sufficient, requires no direct supervision, and mentors/coaches others. The Principal Developer has extensive knowledge/experience across multiple technologies and business areas.\n• Leads the design, development, and planning for solutions and technology standards to solve complex business problems\n• Hands-on development, Support and solve software systems as required, optimizing performance, resolving problems, and providing follow-up on all issues and solutions\n• Collaborate with back-end developers to define required services and implement solutions using these services\n• Responsible for full development life cycle from planning through successful release and support\n• Mentor and assist in the training and onboarding of new team members\n• Participate in code reviews to maintain high quality, well architected code\n• Consults across multiple United Information Technology projects and technology areas to perform fixes, problem management, root-cause analysis, and solution implementation\n• Serves as a resource for technology/project development review and technical assessments\n• Provide consultation and technical leadership in project life cycle planning\n• Ensures consistency and coherence to the enterprise standards and guiding principles throughout the application lifecycle\n• Finds opportunities to leverage/influence the direction for existing infrastructure and application components\n• Understands and applies the enterprise vision and strategy to the project solution while balancing tactical needs to deliver\n• Partner with various business and IT collaborators in defining domain architecture strategy\n\nUnited Airlines is an equal opportunity employer. United Airlines recruits, employs, trains, compensates, and promotes regardless of race, religion, color, national origin, gender identity, sexual orientation, physical ability, age, veteran status, and other protected status as required by applicable law.\nQualifications\n\nRequired\n• Bachelors in Computer Science/Information Technology or related field\n• 5+ years of experience in in full-stack development with a focus on React, Typescript, and Node.js\n• Proficient in web development using React, Redux, ES6, Node.js, HTML5, CSS3\n• 5+ years of experience with common front-end development tools such as Babel, Webpack, NPM, etc.\n• 5 + years of experience building web applications with Micro frontend architecture\n• 5+ years of experience in design patterns and enterprise standards in application design\n• A deep understanding of accessibility fundamentals and its applications in creating robust user interfaces\n• Experience with unit testing\n• Understands Technology systems & applications\n• Exceptional at coding and on time delivery of quality components and or applications\n• Exceptional at triage or analysis of situations for production support\n• Effective participant of requirements gathering, requirements analysis\n• Must be legally authorized to work in the United States for any employer without sponsorship\n\nPreferred\n• Experience developing rest apis using c#\n• Cloud technologies AWS including CDN\n• UI Analytics (Google Analytics, Quantum Metrics)\n• Application performing tools\n• Git/GitHub Code repositories\n\nAirline Maintenance systems development is a PLUS\n\nEqual Opportunity Employer - Minorities/Women/Veterans/Disabled/LGBT',
			job_is_remote: false,
			job_posted_at_timestamp: 1712793600,
			job_posted_at_datetime_utc: '2024-04-11T00:00:00.000Z',
			job_city: 'Chicago',
			job_state: 'IL',
			job_country: 'US',
			job_latitude: 41.878113,
			job_longitude: -87.6298,
			job_benefits: ['retirement_savings', 'health_insurance'],
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=o-wK-4w8ZR5DaDUTAAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: null,
			job_offer_expiration_timestamp: null,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 60,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: true,
				degree_preferred: false,
				professional_certification_mentioned: false,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'Bachelors in Computer Science/Information Technology or related field',
					'5+ years of experience in in full-stack development with a focus on React, Typescript, and Node.js',
					'Proficient in web development using React, Redux, ES6, Node.js, HTML5, CSS3',
					'5+ years of experience with common front-end development tools such as Babel, Webpack, NPM, etc',
					'5 + years of experience building web applications with Micro frontend architecture',
					'5+ years of experience in design patterns and enterprise standards in application design',
					'A deep understanding of accessibility fundamentals and its applications in creating robust user interfaces',
					'Experience with unit testing',
					'Understands Technology systems & applications',
					'Exceptional at coding and on time delivery of quality components and or applications',
					'Exceptional at triage or analysis of situations for production support',
					'Effective participant of requirements gathering, requirements analysis',
					'Must be legally authorized to work in the United States for any employer without sponsorship',
				],
				Responsibilities: [
					'The Senior Developer plays a Critical role in creating and maintaining the strategic partnership between business needs and technology delivery',
					"The Senior Developer's role is to lead the efforts to plan, design, develop and launch efficient systems and solutions in support of core organizational functions",
					'This individual will apply proven communication, analytical and problem-solving skills to help identify, communicate and resolve issues, opportunities or problems in order to enhance the benefit of IT and Business investments',
					'Leads the design, development, and planning for solutions and technology standards to solve complex business problems',
					'Hands-on development, Support and solve software systems as required, optimizing performance, resolving problems, and providing follow-up on all issues and solutions',
					'Collaborate with back-end developers to define required services and implement solutions using these services',
					'Responsible for full development life cycle from planning through successful release and support',
					'Mentor and assist in the training and onboarding of new team members',
					'Participate in code reviews to maintain high quality, well architected code',
					'Consults across multiple United Information Technology projects and technology areas to perform fixes, problem management, root-cause analysis, and solution implementation',
					'Serves as a resource for technology/project development review and technical assessments',
					'Provide consultation and technical leadership in project life cycle planning',
					'Ensures consistency and coherence to the enterprise standards and guiding principles throughout the application lifecycle',
					'Finds opportunities to leverage/influence the direction for existing infrastructure and application components',
					'Understands and applies the enterprise vision and strategy to the project solution while balancing tactical needs to deliver',
				],
			},
			job_job_title: 'Senior',
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
			job_occupational_categories: ['Digital Technology, Corporate'],
			job_naics_code: '481111',
			job_naics_name: 'Scheduled Passenger Air Transportation',
		},
		{
			job_id: 'H-6fEhvXucsQ9n42AAAAAA==',
			employer_name: 'Cognizant Technology Solutions',
			employer_logo: 'https://news.cognizant.com/images/COG-Logo.svg',
			employer_website: 'http://www.cognizant.com',
			employer_company_type: 'Computer Services',
			job_publisher: 'Cognizant',
			job_employment_type: 'FULLTIME',
			job_title: 'Sr. React Developer (Hybrid)',
			job_apply_link: 'https://careers.cognizant.com/global/en/job/00058704661/Sr-React-Developer-Hybrid',
			job_apply_is_direct: false,
			job_apply_quality_score: 0.7891,
			apply_options: [
				{
					publisher: 'Cognizant',
					apply_link: 'https://careers.cognizant.com/global/en/job/00058704661/Sr-React-Developer-Hybrid',
					is_direct: false,
				},
				{
					publisher: 'Indeed',
					apply_link: 'https://www.indeed.com/viewjob?jk=12adf3016cc8e772',
					is_direct: false,
				},
				{
					publisher: 'Diversity Jobs',
					apply_link:
						'https://diversityjobs.com/career/7759712/Sr-React-Developer-Hybrid-Pennsylvania-Philadelphia',
					is_direct: false,
				},
				{
					publisher: 'WJHL Jobs',
					apply_link:
						'https://jobs.wjhl.com/jobs/sr.-react-developer-hybrid-philadelphia-pennsylvania/1291407290-2/',
					is_direct: false,
				},
				{
					publisher: 'LinkedIn',
					apply_link: 'https://www.linkedin.com/jobs/view/sr-react-developer-hybrid-at-cognizant-3893781364',
					is_direct: false,
				},
				{
					publisher: 'Big Country Jobs',
					apply_link:
						'https://jobs.bigcountryhomepage.com/jobs/sr.-react-developer-hybrid-philadelphia-pennsylvania/1291407290-2/',
					is_direct: false,
				},
				{
					publisher: 'Snagajob',
					apply_link: 'https://www.snagajob.com/jobs/930911376',
					is_direct: false,
				},
				{
					publisher: 'KSNT Jobs',
					apply_link:
						'https://jobs.ksnt.com/jobs/sr.-react-developer-hybrid-philadelphia-pennsylvania/1291407290-2/',
					is_direct: false,
				},
			],
			job_description:
				'Sr. React Developer (Hybrid)\n\nLocation: Philadelphia PA, Mount Laurel, NJ (Hybrid)\n\nResponsibilities:\n• This role will focus on the technical processes related to software development and will assist in maintaining the high quality of new software systems, ensuring the software project security, and work to keep new technology by utilization of new tools and trends\n• Write effective APIs contracts and API implementations.\n• Participating in the design and creation of scalable software\n• Work as part of a development team in a fast paced environment\n\nRequired Qualifications:\n• 7 to 10 years of software development experience\n• Proven experience as a Full Stack Developer or similar role\n• Knowledge of front-end JavaScript frameworks (e.g., Angular, React, Next.js, Node.js)\n• Knowledge of back-end development with Python and Node\n• Familiarity with databases (e.g., MYSQL and LDAP) and UI/UX design\n• Knowledge of professional software engineering practices & standard methodologies for the full software creation process, including coding standards, code reviews, source control management (Git, Gitlow), build processes (Maven), testing, and operations.\n• Experience debugging and performance tuning applications and services.\n• Familiarity with DevSecOps, automation releases, CI/CD pipelines would be an added advantage.\n• Working experience writing programmatic compliance checks\n• Expertise in ReactJS and Node. JS development\n• Expertise in UI development using ReactJS, have expertise in HTML5/CSS3Expertise in client-side JavaScript framework like React, jQuery\n• Experience in building Node. JS concepts (Such as event loop, cluster, memory management)Strong experience of building RESTful web services\n• Strong experience in RDBMS databases\n• Excellent communication and collaboration skills\n• Great attention to detail\n\nBenefits: Cognizant offers the following benefits for this position, subject to applicable eligibility requirements:\n• Medical/Dental/Vision/Life Insurance\n• Paid holidays plus Paid Time Off\n• 401(k) plan and contributions\n• Long-term/Short-term Disability\n• Paid Parental Leave\n• Employee Stock Purchase Plan\n\nApplications will be accepted until 04/29/2024.\n\nThe annual salary for this position is between $107,000 – $130,000.00 depending on experience and other qualifications of the successful candidate.\n\nWhy Chose Cognizant?\n\nOur associates enjoy robust benefits and training opportunities from our industry recognized, award winning Academy team. You will have access to hundreds of technical trainings to keep your abilities fresh and have opportunities to acquire certifications on the newest technologies.\n\nIf you became comfortable with ambiguity, delight by change, and excel through autonomy, we’d love to hear from you!\n\nCognizant is an equal opportunity employer provider and committed to creating a diverse environment. We consider all applicants without regard to race, creed, color, national origin, ancestry, age, marital and family status, disabilities, sexual orientation or preference, veteran status or any other classification protected by state, federal or local law.\n\nAbout Cognizant:\n\nHeadquartered in the U.S, Cognizant leverages a highly flexible business model, a flawless global delivery network, and deep domain expertise to deliver to a long list of world-class companies that are leaders in their own space.\n\nwww.cognizant.com',
			job_is_remote: false,
			job_posted_at_timestamp: 1712793600,
			job_posted_at_datetime_utc: '2024-04-11T00:00:00.000Z',
			job_city: 'Philadelphia',
			job_state: 'PA',
			job_country: 'US',
			job_latitude: 39.952583,
			job_longitude: -75.16522,
			job_benefits: ['dental_coverage', 'paid_time_off', 'retirement_savings', 'health_insurance'],
			job_google_link:
				'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=H-6fEhvXucsQ9n42AAAAAA%3D%3D',
			job_offer_expiration_datetime_utc: null,
			job_offer_expiration_timestamp: null,
			job_required_experience: {
				no_experience_required: false,
				required_experience_in_months: 84,
				experience_mentioned: true,
				experience_preferred: false,
			},
			job_required_skills: null,
			job_required_education: {
				postgraduate_degree: false,
				professional_certification: false,
				high_school: false,
				associates_degree: false,
				bachelors_degree: false,
				degree_mentioned: false,
				degree_preferred: false,
				professional_certification_mentioned: true,
			},
			job_experience_in_place_of_education: false,
			job_min_salary: null,
			job_max_salary: null,
			job_salary_currency: null,
			job_salary_period: null,
			job_highlights: {
				Qualifications: [
					'7 to 10 years of software development experience',
					'Proven experience as a Full Stack Developer or similar role',
					'Knowledge of front-end JavaScript frameworks (e.g., Angular, React, Next.js, Node.js)',
					'Knowledge of back-end development with Python and Node',
					'Familiarity with databases (e.g., MYSQL and LDAP) and UI/UX design',
					'Knowledge of professional software engineering practices & standard methodologies for the full software creation process, including coding standards, code reviews, source control management (Git, Gitlow), build processes (Maven), testing, and operations',
					'Experience debugging and performance tuning applications and services',
					'Familiarity with DevSecOps, automation releases, CI/CD pipelines would be an added advantage',
					'Working experience writing programmatic compliance checks',
					'Expertise in ReactJS and Node',
					'Expertise in UI development using ReactJS, have expertise in HTML5/CSS3Expertise in client-side JavaScript framework like React, jQuery',
					'Experience in building Node',
					'JS concepts (Such as event loop, cluster, memory management)Strong experience of building RESTful web services',
					'Strong experience in RDBMS databases',
					'Excellent communication and collaboration skills',
				],
				Responsibilities: [
					'This role will focus on the technical processes related to software development and will assist in maintaining the high quality of new software systems, ensuring the software project security, and work to keep new technology by utilization of new tools and trends',
					'Write effective APIs contracts and API implementations',
					'Participating in the design and creation of scalable software',
					'Work as part of a development team in a fast paced environment',
				],
				Benefits: [
					'Medical/Dental/Vision/Life Insurance',
					'Paid holidays plus Paid Time Off',
					'401(k) plan and contributions',
					'Long-term/Short-term Disability',
					'Paid Parental Leave',
					'Employee Stock Purchase Plan',
					'The annual salary for this position is between $107,000 – $130,000.00 depending on experience and other qualifications of the successful candidate',
					'You will have access to hundreds of technical trainings to keep your abilities fresh and have opportunities to acquire certifications on the newest technologies',
				],
			},
			job_job_title: null,
			job_posting_language: 'en',
			job_onet_soc: '15113400',
			job_onet_job_zone: '3',
			job_occupational_categories: ['Digital'],
			job_naics_code: '541511',
			job_naics_name: 'Custom Computer Programming Services',
		},
	],
};
